import Foundation

enum BirdPatternsData {
    static let patterns: [SpeciesReferenceData.Pattern] = [
        Pattern(id: 21, signal: "Pinning eyes (pupils contracting)", context: "New environment", meaning: "Alertness or agitation — pupils pin when excited or threatened.", confidence: "Common", category: "Eyes", actionTip: "Speak softly and avoid sudden movements."),
        Pattern(id: 22, signal: "Feather fluffing + shaking", context: "After bath/preen", meaning: "Comfort and grooming — normal maintenance behavior after cleaning.", confidence: "Very common", category: "Feathers", actionTip: "Ensure room is warm after bathing."),
        Pattern(id: 23, signal: "Beak grinding", context: "Settling to sleep", meaning: "Contentment — bird is relaxed and ready to rest.", confidence: "Very common", category: "Beak", actionTip: "Keep lights dim; avoid handling."),
        Pattern(id: 24, signal: "Wing spreading", context: "When approached", meaning: "Threat display or balancing — context determines if defensive or stretching.", confidence: "Common", category: "Wings", actionTip: "Step back if accompanied by hissing or lunging."),
        Pattern(id: 25, signal: "Head bobbing", context: "During interaction", meaning: "Excitement or curiosity — engaged with stimulus or person.", confidence: "Common", category: "Body", actionTip: "Engage with safe toys; avoid over-stimulation."),
        Pattern(id: 26, signal: "Clicking/tongue sounds", context: "With owner", meaning: "Social bonding — bird mimicking human sounds or showing affection.", confidence: "Very common", category: "Vocal", actionTip: "Click back gently to reinforce bonding."),
        Pattern(id: 27, signal: "Screaming", context: "When alone", meaning: "Separation distress or boredom — flock animals dislike isolation.", confidence: "Very common", category: "Vocal", actionTip: "Gradual alone-time training and background audio."),
        Pattern(id: 28, signal: "Mouth open + panting", context: "Hot environment", meaning: "Heat stress — birds cannot sweat; panting is an emergency sign.", confidence: "Common", category: "Health", actionTip: "Move to shade, offer water, consult vet if persistent."),
        Pattern(id: 29, signal: "Regurgitating food", context: "For owner", meaning: "Courtship bonding — bird sees you as mate; not hunger.", confidence: "Common", category: "Bonding", actionTip: "Redirect to toys; avoid encouraging hormonal cycles."),
        Pattern(id: 30, signal: "Sleeping on one foot", context: "Nighttime", meaning: "Normal thermoregulation — sign of a healthy, relaxed bird.", confidence: "Very common", category: "Rest", actionTip: "Maintain consistent sleep schedule with cover."),
        Pattern(id: 141, signal: "Wing flipping", context: "After landing", meaning: "Resetting feathers — quick flicks settle plumage.", confidence: "Very common", category: "Wings", actionTip: "Normal; note if excessive (pain or itch)."),
        Pattern(id: 142, signal: "Tail fanning", context: "Mirror reflection", meaning: "Territory or mate response — reflection triggers social instincts.", confidence: "Common", category: "Tail", actionTip: "Cover mirrors during hormonal seasons."),
        Pattern(id: 143, signal: "Beak wiping on perch", context: "After eating", meaning: "Cleaning — removing food residue from beak.", confidence: "Very common", category: "Beak", actionTip: "Provide clean perches of varied textures."),
        Pattern(id: 144, signal: "Hanging upside down", context: "Playtime", meaning: "Play and confidence — comfortable birds explore acrobatically.", confidence: "Common", category: "Play", actionTip: "Offer safe climbing structures."),
        Pattern(id: 145, signal: "Pacing on perch", context: "Before bedtime", meaning: "Routine anticipation — bird expects cover or quiet time.", confidence: "Common", category: "Routine", actionTip: "Keep bedtime consistent within 30 minutes."),
        Pattern(id: 146, signal: "Feather picking", context: "After household change", meaning: "Stress or medical issue — requires vet evaluation if persistent.", confidence: "Common", category: "Health", actionTip: "Log triggers; schedule avian vet visit."),
        Pattern(id: 147, signal: "Soft chattering", context: "Watching outdoor birds", meaning: "Social vocalization — communicating with distant flock.", confidence: "Very common", category: "Vocal", actionTip: "Allow window time safely behind glass."),
        Pattern(id: 148, signal: "Body flattening", context: "Unfamiliar hands", meaning: "Fear — bird trying to appear smaller and avoid contact.", confidence: "Common", category: "Stress", actionTip: "Train step-up with treats at bird's pace."),
        Pattern(id: 149, signal: "Dancing + hopping", context: "Favorite music", meaning: "Joy and rhythm response — positive stimulation.", confidence: "Common", category: "Play", actionTip: "Use as enrichment; keep volume moderate."),
        Pattern(id: 150, signal: "Beak tapping on cage", context: "Morning", meaning: "Attention request — learned that tapping summons owner.", confidence: "Very common", category: "Routine", actionTip: "Respond after a brief pause to avoid reinforcing noise."),
        Pattern(id: 151, signal: "Wing drooping", context: "Afternoon heat", meaning: "Overheating or illness — drooped wings can signal distress.", confidence: "Common", category: "Health", actionTip: "Check temperature and hydration immediately."),
        Pattern(id: 152, signal: "Shivering", context: "After shower mist", meaning: "Cold or fear — distinguish wet chill from anxiety tremor.", confidence: "Common", category: "Health", actionTip: "Dry gently and warm the room."),
        Pattern(id: 153, signal: "Foot tapping", context: "New toy introduction", meaning: "Investigation — testing object stability before stepping on.", confidence: "Common", category: "Exploration", actionTip: "Leave toy in view for gradual acceptance."),
        Pattern(id: 154, signal: "Neck stretching long", context: "After nap", meaning: "Stretching — relieves muscle tension like a yawn.", confidence: "Very common", category: "Body", actionTip: "Normal; offer varied perch diameters."),
        Pattern(id: 155, signal: "Hissing", context: "During cage cleaning", meaning: "Protecting territory — routine disruption feels threatening.", confidence: "Common", category: "Territory", actionTip: "Clean in stages; let bird observe from safe perch."),
        Pattern(id: 156, signal: "Mantling over food", context: "With cagemate", meaning: "Resource guarding — protecting valued food item.", confidence: "Common", category: "Social", actionTip: "Separate feeding stations if repeated."),
        Pattern(id: 157, signal: "Quiet fluff + eyes closed", context: "Rainy afternoon", meaning: "Nap mode — low stimulation encourages rest.", confidence: "Very common", category: "Rest", actionTip: "Dim lights; avoid loud household activity."),
        Pattern(id: 158, signal: "Rapid tail wag (side to side)", context: "Excited greeting", meaning: "Happiness in some species — unlike mammal tail wag meaning.", confidence: "Common", category: "Tail", actionTip: "Greet calmly to prevent over-excitement crashes."),
        Pattern(id: 159, signal: "Beak grinding + eyes pinning", context: "Favorite person enters", meaning: "High arousal affection — strong positive association.", confidence: "Common", category: "Bonding", actionTip: "Offer a short training session to channel energy."),
        Pattern(id: 160, signal: "Refusing to step up", context: "After travel", meaning: "Stress residue — bird needs time to feel safe again.", confidence: "Common", category: "Stress", actionTip: "Wait 20–30 minutes before asking for step-up.")
    ]

    private typealias Pattern = SpeciesReferenceData.Pattern
}
