import Foundation

enum CatPatternsData {
    static let patterns: [SpeciesReferenceData.Pattern] = [
        Pattern(id: 11, signal: "Slow blink", context: "Looking at owner", meaning: "Cat kiss — deep trust. Blink back slowly to reciprocate affection.", confidence: "Very common", category: "Eyes", actionTip: "Blink back within a few seconds to strengthen trust."),
        Pattern(id: 12, signal: "Kneading (making biscuits)", context: "On owner's lap", meaning: "Kitten comfort behavior carried into adulthood — deep contentment.", confidence: "Very common", category: "Paws", actionTip: "Trim nails if kneading is uncomfortable on skin."),
        Pattern(id: 13, signal: "Ears flat back + hissing", context: "Near new animal", meaning: "Fear aggression — cat feels trapped and may strike if cornered.", confidence: "Very common", category: "Ears", actionTip: "Provide escape routes and separate animals immediately."),
        Pattern(id: 14, signal: "Tail puffed up", context: "Loud noises", meaning: "Fear response — puffing makes the cat appear larger to threats.", confidence: "Common", category: "Tail", actionTip: "Offer a quiet hiding spot; do not chase or pick up."),
        Pattern(id: 15, signal: "Chattering teeth", context: "Watching birds through window", meaning: "Frustrated predatory instinct — can't reach prey behind glass.", confidence: "Common", category: "Vocal", actionTip: "Normal hunting frustration; add window perches for enrichment."),
        Pattern(id: 16, signal: "Head bunting", context: "Against owner", meaning: "Scent marking — 'you're mine' through facial pheromone glands.", confidence: "Very common", category: "Bonding", actionTip: "Accept the bunt; it's a compliment."),
        Pattern(id: 17, signal: "Ears forward + dilated pupils", context: "Play session", meaning: "High arousal play mode — may switch between play and overstimulation quickly.", confidence: "Common", category: "Play", actionTip: "Use wand toys; end session before overstimulation."),
        Pattern(id: 18, signal: "Showing belly", context: "On back near owner", meaning: "Trust display — NOT always an invitation to rub the stomach.", confidence: "Common", category: "Posture", actionTip: "Pet the head or cheeks unless the cat clearly invites belly rubs."),
        Pattern(id: 19, signal: "Tail wrapped around owner", context: "Sitting together", meaning: "Affection bond — feline equivalent of holding hands.", confidence: "Common", category: "Tail", actionTip: "Stay still and enjoy; sudden moves may end the moment."),
        Pattern(id: 20, signal: "Trilling vocalization", context: "Greeting", meaning: "Happy greeting — mother-to-kitten sound extended to trusted humans.", confidence: "Very common", category: "Vocal", actionTip: "Respond softly; trills often invite follow-me behavior."),
        Pattern(id: 121, signal: "Tail twitch at tip", context: "During petting", meaning: "Irritation building — stop petting before a swat or bite.", confidence: "Very common", category: "Tail", actionTip: "Pause petting and watch if the cat re-engages."),
        Pattern(id: 122, signal: "Ears rotated sideways", context: "Ambiguous sounds", meaning: "Uncertainty — cat is assessing whether a sound is a threat.", confidence: "Common", category: "Ears", actionTip: "Reduce noise sources if the cat seems anxious."),
        Pattern(id: 123, signal: "Hiding under furniture", context: "After visitors leave", meaning: "Recovery time — cat needs decompression after social stress.", confidence: "Very common", category: "Stress", actionTip: "Leave food and water nearby; don't drag them out."),
        Pattern(id: 124, signal: "Scratching vertical surfaces", context: "Near doorways", meaning: "Territory marking and claw maintenance — not spiteful destruction.", confidence: "Very common", category: "Territory", actionTip: "Place scratching posts at key pathways."),
        Pattern(id: 125, signal: "Staring without blinking", context: "Facing another cat", meaning: "Challenge or tension — prolonged stare can escalate conflict.", confidence: "Common", category: "Social", actionTip: "Block sightlines or use vertical space to separate."),
        Pattern(id: 126, signal: "Bringing prey toys", context: "Nighttime", meaning: "Hunting gift behavior — cat shares 'catch' with their social group.", confidence: "Common", category: "Hunting", actionTip: "Praise briefly; rotate interactive toys before bed."),
        Pattern(id: 127, signal: "Excessive grooming one spot", context: "After schedule change", meaning: "Possible stress or skin issue — over-grooming can cause bald patches.", confidence: "Common", category: "Stress", actionTip: "Log frequency; consult a vet if skin breaks."),
        Pattern(id: 128, signal: "Knocking objects off tables", context: "When alone", meaning: "Attention seeking or play — cat learns it reliably summons humans.", confidence: "Very common", category: "Play", actionTip: "Schedule play sessions; ignore the behavior when possible."),
        Pattern(id: 129, signal: "Crouched low + wide eyes", context: "New furniture delivery", meaning: "Fear of novel objects — cats prefer predictable environments.", confidence: "Common", category: "Stress", actionTip: "Introduce new items gradually with treats nearby."),
        Pattern(id: 130, signal: "Purring while eating", context: "Mealtime", meaning: "Contentment — purring during meals is usually positive.", confidence: "Very common", category: "Vocal", actionTip: "Maintain consistent feeding routine."),
        Pattern(id: 131, signal: "Night zoomies", context: "After dusk", meaning: "Crepuscular energy burst — normal for many indoor cats.", confidence: "Very common", category: "Activity", actionTip: "Pre-bed play session can reduce midnight chaos."),
        Pattern(id: 132, signal: "Tail straight up", context: "Walking toward owner", meaning: "Confident friendly greeting — happy to see you.", confidence: "Very common", category: "Tail", actionTip: "Greet at their level with a calm voice."),
        Pattern(id: 133, signal: "Half-closed eyes while sitting", context: "Sunny window spot", meaning: "Relaxed vigilance — cat feels safe enough to rest lightly.", confidence: "Very common", category: "Rest", actionTip: "Avoid startling; let them nap."),
        Pattern(id: 134, signal: "Hissing without contact", context: "Vet waiting room", meaning: "Distance-increasing signal — cat asks for more space.", confidence: "Very common", category: "Stress", actionTip: "Cover carrier with a towel; face away from other animals."),
        Pattern(id: 135, signal: "Rubbing cheeks on corners", context: "New home", meaning: "Scent mapping — depositing facial pheromones to claim space.", confidence: "Very common", category: "Territory", actionTip: "Allow rubbing; use pheromone diffusers during moves."),
        Pattern(id: 136, signal: "Lying with paws tucked", context: "Quiet afternoon", meaning: "Loaf position — relaxed but ready to move if needed.", confidence: "Very common", category: "Rest", actionTip: "A good moment for gentle petting if invited."),
        Pattern(id: 137, signal: "Swatting without claws", context: "During play", meaning: "Play inhibition practice — kitten-learned control of bite/claw force.", confidence: "Common", category: "Play", actionTip: "Use toys, not hands, as play targets."),
        Pattern(id: 138, signal: "Meowing at closed doors", context: "Morning", meaning: "Learned routine cue — cat associates time/location with resources.", confidence: "Very common", category: "Routine", actionTip: "Feed after a quiet moment to avoid reinforcing loud meows."),
        Pattern(id: 139, signal: "Tail wrapped around own body", context: "Cold weather", meaning: "Thermoregulation and comfort — conserving warmth.", confidence: "Common", category: "Rest", actionTip: "Offer a warm bed if they seek heat often."),
        Pattern(id: 140, signal: "Staring at water bowl", context: "Before drinking", meaning: "Preference for moving water — many cats distrust still bowls.", confidence: "Common", category: "Hydration", actionTip: "Try a fountain or refresh water frequently.")
    ]

    private typealias Pattern = SpeciesReferenceData.Pattern
}
