import Foundation

enum DogPatternsData {
    static let patterns: [SpeciesReferenceData.Pattern] = [
        Pattern(id: 1, signal: "Tail wagging + high", context: "When greeting owner", meaning: "Excitement and happiness — tail wag speed correlates with arousal level. A loose, wide wag usually means genuine joy.", confidence: "Very common", category: "Tail", actionTip: "Return the greeting calmly; avoid overwhelming with loud voices."),
        Pattern(id: 2, signal: "Tail tucked", context: "Around strangers", meaning: "Fear or anxiety — the dog is trying to appear smaller and non-threatening. May escalate to flight if pressure continues.", confidence: "Very common", category: "Tail", actionTip: "Create distance from the trigger and let the dog approach on their own terms."),
        Pattern(id: 3, signal: "Ears pinned back", context: "During vet visits", meaning: "Stress submission — ears flatten against the skull when the dog feels unsafe or overwhelmed.", confidence: "Common", category: "Ears", actionTip: "Use high-value treats and let the dog sniff the room before handling."),
        Pattern(id: 4, signal: "Play bow (front down, rear up)", context: "With other dogs", meaning: "Invitation to play — a meta-signal saying everything that follows is play, not aggression.", confidence: "Very common", category: "Posture", actionTip: "Allow supervised play; interrupt if body tension rises."),
        Pattern(id: 5, signal: "Whale eye (showing whites)", context: "During handling", meaning: "Discomfort — the dog turns their head away but keeps eyes on the handler, exposing sclera.", confidence: "Common", category: "Eyes", actionTip: "Stop or slow down the interaction immediately."),
        Pattern(id: 6, signal: "Lip licking (no food)", context: "After scolding", meaning: "Appeasement signal — 'I mean no harm' rather than guilt in the human sense.", confidence: "Common", category: "Face", actionTip: "Switch to positive reinforcement instead of verbal correction."),
        Pattern(id: 7, signal: "Yawning (no tiredness)", context: "During training", meaning: "Stress or overstimulation — a displacement behavior to self-regulate arousal.", confidence: "Common", category: "Face", actionTip: "Take a break, lower criteria, and shorten the session."),
        Pattern(id: 8, signal: "Slow blink + soft eyes", context: "Calm moments", meaning: "Deep trust and relaxation — your dog feels safe in your presence.", confidence: "Very common", category: "Eyes", actionTip: "Blink back slowly to reinforce the bond."),
        Pattern(id: 9, signal: "Shaking off (body shake)", context: "After tense moment", meaning: "Stress release — literally shaking off residual tension from a stressful event.", confidence: "Common", category: "Body", actionTip: "Note what preceded the shake; it marks a stress peak."),
        Pattern(id: 10, signal: "Sniffing ground repeatedly", context: "During walks", meaning: "Decompression — sniffing is calming and mentally enriching for dogs.", confidence: "Very common", category: "Exploration", actionTip: "Allow sniff breaks; they are not stalling."),
        Pattern(id: 101, signal: "Stiff tail + slow wag", context: "Near unfamiliar dogs", meaning: "Caution or potential conflict — not a friendly wag. Body may be tense and forward.", confidence: "Common", category: "Tail", actionTip: "Increase distance and avoid tight leash pressure."),
        Pattern(id: 102, signal: "Hackles raised", context: "Sudden noises", meaning: "Arousal — can indicate fear, excitement, or aggression depending on context.", confidence: "Common", category: "Body", actionTip: "Read the whole body; do not assume aggression alone."),
        Pattern(id: 103, signal: "Paw lift", context: "Uncertain situations", meaning: "Hesitation or mild anxiety — the dog is unsure how to proceed.", confidence: "Common", category: "Posture", actionTip: "Give clearer cues and reduce environmental pressure."),
        Pattern(id: 104, signal: "Turning away", context: "When approached head-on", meaning: "Polite refusal of interaction — dog is asking for space.", confidence: "Very common", category: "Social", actionTip: "Approach from the side and avoid direct eye contact."),
        Pattern(id: 105, signal: "Freezing in place", context: "During grooming", meaning: "Shut-down stress — dog is too overwhelmed to move; not calm compliance.", confidence: "Common", category: "Stress", actionTip: "Pause grooming and rebuild tolerance in short sessions."),
        Pattern(id: 106, signal: "Mouth closed + hard stare", context: "Resource guarding", meaning: "Tension around valued items — may precede a growl or snap.", confidence: "Common", category: "Social", actionTip: "Trade for treats; never punish growling."),
        Pattern(id: 107, signal: "Pacing", context: "Before owner leaves", meaning: "Anticipatory anxiety — often linked to separation distress.", confidence: "Common", category: "Anxiety", actionTip: "Practice calm departures and enrichment toys."),
        Pattern(id: 108, signal: "Excessive drooling", context: "Car rides", meaning: "Stress or motion sickness — not always hunger-related.", confidence: "Common", category: "Stress", actionTip: "Acclimate slowly to the car with positive associations."),
        Pattern(id: 109, signal: "Digging", context: "In the yard", meaning: "Breed instinct, boredom, or temperature regulation — context matters.", confidence: "Very common", category: "Exploration", actionTip: "Provide a designated dig pit or more mental exercise."),
        Pattern(id: 110, signal: "Circling before lying down", context: "Bedtime", meaning: "Nesting instinct — trampling down an imaginary bed for comfort.", confidence: "Very common", category: "Rest", actionTip: "Normal behavior; no intervention needed."),
        Pattern(id: 111, signal: "Soft whimpering", context: "At the door", meaning: "Anticipation — often excitement for a walk or owner's return.", confidence: "Very common", category: "Vocal", actionTip: "Wait for quiet before opening the door to avoid reinforcing noise."),
        Pattern(id: 112, signal: "Hard stare at door", context: "Evening routine", meaning: "Expectation — dog has learned a predictable schedule cue.", confidence: "Common", category: "Routine", actionTip: "Vary routines slightly to reduce fixation."),
        Pattern(id: 113, signal: "Rolling on back", context: "During play", meaning: "Play submission — inviting continued gentle play, not always belly rub request.", confidence: "Common", category: "Play", actionTip: "Keep play gentle; stop if teeth or claws escalate."),
        Pattern(id: 114, signal: "Nose nudge", context: "While you work", meaning: "Attention seeking — polite request for interaction.", confidence: "Very common", category: "Social", actionTip: "Acknowledge briefly or redirect to a chew toy."),
        Pattern(id: 115, signal: "Leaning into legs", context: "On the couch", meaning: "Affection and security seeking — physical contact soothes many dogs.", confidence: "Very common", category: "Bonding", actionTip: "Enjoy the moment; set boundaries if weight is uncomfortable."),
        Pattern(id: 116, signal: "Low growl during tug", context: "Play with toy", meaning: "Play growl — usually loose body and wagging tail accompany it.", confidence: "Common", category: "Play", actionTip: "Stop if body stiffens or growl deepens."),
        Pattern(id: 117, signal: "Sniffing another dog's rear", context: "Park greeting", meaning: "Normal canine greeting ritual — gathering chemical information.", confidence: "Very common", category: "Social", actionTip: "Allow brief sniff; interrupt if either dog stiffens."),
        Pattern(id: 118, signal: "Submissive urination", context: "When greeted loudly", meaning: "Fear or appeasement — common in young or sensitive dogs.", confidence: "Common", category: "Stress", actionTip: "Greet calmly at their level; avoid leaning over."),
        Pattern(id: 119, signal: "Head tilt", context: "Unfamiliar sounds", meaning: "Curiosity — adjusting ear position to localize a sound.", confidence: "Very common", category: "Ears", actionTip: "Charming but also a good moment to capture in your journal."),
        Pattern(id: 120, signal: "Following room to room", context: "Owner moving around home", meaning: "Velcro behavior — attachment or boredom, depending on breed and history.", confidence: "Very common", category: "Bonding", actionTip: "Reward independent settle on a mat.")
    ]

    private typealias Pattern = SpeciesReferenceData.Pattern
}
